In [3]:
import pandas as pd
import numpy as np

In [4]:
# 加载数据
train_df = pd.read_csv('./data/train.csv')
test_df = pd.read_csv('./data/test.csv')

In [5]:
# 查看DataFrame信息
train_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.0,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.0,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vande...",female,31.0,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.0,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.0,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.0,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.0,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.0,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...",female,38.0,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.0,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
861,862,0,2,"Giles, Mr. Frederick Edward",male,21.0,1,0,28134,11.5000,NaN,S
862,863,1,1,"Swift, Mrs. Frederick Joel (Margaret Welles Ba...",female,48.0,0,0,17466,25.9292,D17,S
863,864,0,3,"Sage, Miss. Dorothy Edith ""Dolly""",female,NaN,8,2,CA. 2343,69.5500,NaN,S
864,865,0,2,"Gill, Mr. John William",male,24.0,0,0,233866,13.0000,NaN,S
865,866,1,2,"Bystrom, Mrs. (Karolina)",female,42.0,0,0,236852,13.0000,NaN,S
866,867,1,2,"Duran y More, Miss. Asuncion",female,27.0,1,0,SC/PARIS 2149,13.8583,NaN,C
867,868,0,1,"Roebling, Mr. Washington Augustus II",male,31.0,0,0,PC 17590,50.4958,A24,S
868,869,0,3,"van Melkebeke, Mr. Philemon",male,NaN,0,0,345777,9.5000,NaN,S
869,870,1,3,"Johnson, Master. Harold Theodor",male,4.0,1,1,347742,11.1333,NaN,S
870,871,0,3,"Balkic, Mr. Cerin",male,26.0,0,0,349248,7.8958,NaN,S
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
873,874,0,3,"Vander Cruyssen, Mr. Victor",male,47.0,0,0,345765,9.0000,NaN,S
874,875,1,2,"Abelson, Mrs. Samuel (Hannah Wizosky)",female,28.0,1,0,P/PP 3381,24.0000,NaN,C
875,876,1,3,"Najib, Miss. Adele Kiamie ""Jane""",female,15.0,0,0,2667,7.2250,NaN,C
876,877,0,3,"Gustafsson, Mr. Alfred Ossian",male,20.0,0,0,7534,9.8458,NaN,S
877,878,0,3,"Petroff, Mr. Nedelio",male,19.0,0,0,349212,7.8958,NaN,S
878,879,0,3,"Laleff, Mr. Kristo",male,NaN,0,0,349217,7.8958,NaN,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
880,881,1,2,"Shelley, Mrs. William (Imanita Parrish Hall)",female,25.0,0,1,230433,26.0000,NaN,S
881,882,0,3,"Markun, Mr. Johann",male,33.0,0,0,349257,7.8958,NaN,S
882,883,0,3,"Dahlberg, Miss. Gerda Ulrika",female,22.0,0,0,7552,10.5167,NaN,S
883,884,0,2,"Banfield, Mr. Frederick James",male,28.0,0,0,C.A./SOTON 34068,10.5000,NaN,S
884,885,0,3,"Sutehall, Mr. Henry Jr",male,25.0,0,0,SOTON/OQ 392076,7.0500,NaN,S
885,886,0,3,"Rice, Mrs. William (Margaret Norton)",female,39.0,0,5,382652,29.1250,NaN,Q
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [6]:
# 计算均值
train_df.mean()

PassengerId    446.000000
Survived         0.383838
Pclass           2.308642
Age             29.699118
SibSp            0.523008
Parch            0.381594
Fare            32.204208
dtype: float64

In [7]:
# 计算某一列均值
train_df['Age'].mean()

29.69911764705882

In [9]:
data_len = len(train_df['Age'])

In [10]:
w = np.random.rand(data_len)
print(w)

[  7.05283681e-01   8.83098097e-01   7.46404051e-01   2.69981784e-01
   5.43277119e-01   3.06413714e-01   4.54433132e-01   8.53314161e-01
   1.26407434e-01   3.99494638e-01   4.14139470e-01   6.37595831e-01
   8.73406327e-01   3.85742515e-01   3.14442826e-01   7.85866210e-01
   1.81380051e-01   7.45167323e-01   6.04888424e-01   8.04524986e-01
   9.47489574e-01   8.52983626e-01   3.15266331e-01   9.16270026e-01
   1.31470699e-01   7.45107341e-01   5.97886837e-01   9.21079559e-01
   6.62929911e-01   4.69936803e-01   5.76262987e-01   6.14221476e-01
   9.73221681e-01   6.86676330e-01   7.54851598e-03   8.02262486e-01
   2.01576568e-01   7.03068487e-01   9.94816428e-01   7.15146426e-01
   4.47226989e-01   9.63102616e-01   5.30483383e-01   9.15601101e-01
   4.20020835e-01   8.46536002e-01   5.39413636e-02   4.05697551e-02
   6.91493996e-01   8.93337524e-01   5.46307961e-01   3.29641627e-01
   8.95629232e-01   8.67421581e-01   2.49575284e-01   9.37321472e-01
   1.35239145e-01   8.26338577e-01   6.45924326e-01   1.89807880e-01
   7.02396714e-01   3.27246906e-01   1.82552171e-01   5.31361901e-01
   9.92813232e-01   1.63354716e-01   4.75784133e-01   4.12896161e-01
   3.04106133e-01   9.41344096e-01   7.41141560e-02   2.49681331e-01
   8.21766761e-01   1.60783242e-02   1.23526450e-02   8.07203364e-01
   2.26629598e-01   7.65905763e-01   6.65600453e-01   1.88223346e-02
   1.95297325e-01   3.14421373e-01   3.06590238e-02   3.20567117e-01
   5.82468280e-01   8.47437570e-01   8.84690390e-01   9.63681724e-01
   5.36398855e-01   7.36761185e-01   9.11581476e-01   9.50572238e-01
   4.97942332e-01   6.65829983e-01   7.22364420e-01   2.65038282e-01
   8.67309430e-01   2.43948156e-01   5.72202906e-01   7.70770417e-01
   8.33288654e-02   6.96087323e-01   2.07963697e-01   6.40141774e-03
   7.11811533e-01   7.43264711e-01   6.78464809e-01   1.05068784e-01
   7.46566669e-01   1.14080150e-02   3.59158487e-01   1.88942147e-01
   3.79973835e-01   9.19773087e-01   1.51303951e-01   5.84161349e-01
   1.60830301e-01   9.20046209e-01   1.81956252e-03   3.63890481e-01
   7.03432059e-01   3.89926073e-01   9.24789823e-01   2.72018018e-01
   5.12395771e-01   9.42772850e-01   1.97710672e-01   9.91180780e-01
   3.51516677e-01   1.11755237e-01   4.91101417e-01   2.66614758e-01
   4.48003693e-02   4.46051547e-01   4.23609544e-01   3.83890237e-01
   4.21613960e-01   6.73320231e-01   5.40931509e-01   4.87705338e-02
   1.84028520e-01   3.66798721e-01   3.68791800e-02   3.84444851e-01
   6.65169566e-02   3.34815492e-01   9.79226732e-01   3.32187380e-01
   5.40889747e-01   5.96773858e-01   3.01945372e-01   2.06274475e-01
   9.77374287e-01   2.80683557e-01   3.00630932e-01   2.15172411e-01
   8.74730824e-01   8.52728078e-01   3.10946054e-01   6.69960945e-01
   7.79620326e-01   7.04280896e-01   8.86528961e-01   2.74022821e-01
   1.14262653e-01   4.60200142e-01   6.22567573e-01   2.48161801e-01
   9.25151137e-01   6.05319946e-01   6.06784808e-01   2.42027206e-01
   2.42684421e-01   6.22955704e-01   2.25197964e-01   9.66686262e-01
   5.86226220e-01   4.50354118e-02   6.08263424e-01   5.56110872e-01
   4.87878842e-01   9.00205348e-01   1.51424152e-01   2.43195252e-02
   4.09550933e-01   8.51424416e-01   2.11195697e-01   2.92788066e-01
   6.65335168e-01   1.42398886e-01   3.23311370e-01   8.55394968e-01
   8.86050091e-02   9.07914726e-01   7.66626112e-01   5.62492248e-01
   7.24808928e-01   8.73945453e-01   5.27692103e-01   3.48275372e-01
   7.83025185e-01   5.16193004e-01   8.20449998e-01   9.64978409e-01
   2.62093181e-01   1.17604695e-01   8.64699347e-01   2.62270354e-01
   9.43086390e-01   7.56252023e-01   6.15471045e-01   6.79128046e-01
   4.37854689e-01   1.73720821e-01   5.39343860e-01   1.88213697e-01
   3.72588295e-01   6.86160913e-01   5.09653606e-01   8.96317734e-01
   8.72014734e-01   3.39408969e-01   5.45233013e-01   2.65907404e-01
   1.10504629e-01   4.96228233e-01   2.93668814e-01   6.39966031e-01
   7.35306055e-01   5.53602704e-01   9.65941608e-01   1.04794735e-01
   2.64360303e-01   8.47875616e-01   6.88578508e-01   1.43232582e-01
   8.31452652e-01   9.68091467e-01   6.17391520e-01   7.93568989e-01
   8.50068523e-01   2.43340137e-01   4.18509634e-01   4.14903181e-01
   2.87926252e-01   5.20030390e-01   6.10657289e-01   9.66803964e-01
   3.13832706e-01   4.83450443e-01   9.76783369e-02   9.85958240e-01
   9.53942808e-01   7.53282666e-01   7.65639067e-01   5.63947390e-01
   4.11668899e-01   4.24243615e-02   8.30789139e-01   1.94938677e-01
   4.26404978e-01   9.33405019e-01   1.02237372e-01   9.90990871e-01
   8.90652473e-01   3.87461135e-01   6.79688660e-01   6.06494107e-01
   2.44237656e-01   3.90912962e-01   1.14942813e-01   3.34779043e-01
   5.67650424e-01   4.27042802e-01   4.47698487e-01   9.18052834e-01
   8.40814987e-01   8.48631162e-01   2.72921492e-02   2.25121308e-01
   8.88612424e-01   2.69084410e-01   3.70794647e-02   6.14581685e-01
   7.24440747e-01   6.29765295e-01   9.97244008e-01   4.04970745e-01
   6.02525188e-01   5.52768641e-01   9.12366881e-01   6.64210301e-01
   2.20816617e-01   4.05424469e-01   5.99072055e-01   9.35459381e-01
   9.41975994e-01   1.50198389e-01   2.80478538e-01   6.15452346e-01
   6.68550865e-01   3.01613213e-01   8.44378221e-01   7.93395589e-01
   2.85302705e-01   7.35675391e-01   6.09223086e-01   7.71993802e-01
   1.01264990e-02   7.35048249e-01   1.84981209e-01   6.95317475e-01
   5.35754056e-01   2.72149466e-01   9.30642405e-01   7.57370649e-01
   7.24646972e-01   3.01770796e-01   9.72457076e-02   4.52928215e-01
   3.37230194e-01   7.34510027e-01   8.85137565e-01   1.41392202e-01
   8.62780138e-01   6.09713079e-01   3.57777084e-01   6.65265591e-01
   6.76440220e-01   2.37255112e-02   8.02762909e-01   8.96752736e-01
   9.12499647e-01   4.05695379e-01   4.90117621e-01   8.29143452e-01
   9.70489459e-01   7.00701425e-01   4.95673948e-01   1.37520284e-01
   4.64767851e-01   2.00299208e-01   7.59015556e-01   5.15998731e-01
   3.03689289e-01   6.22979939e-02   7.12094815e-01   7.68072722e-01
   5.63433078e-01   4.60671264e-01   7.55045243e-01   6.73717019e-02
   9.15759731e-01   2.68447238e-01   5.78937353e-01   4.31859932e-01
   7.68872249e-01   1.07936226e-01   7.32053430e-01   2.00142993e-01
   4.70828646e-01   3.41123794e-02   9.98126649e-01   9.10378218e-01
   8.26628442e-01   3.63842621e-01   8.00534959e-01   5.84615635e-01
   5.03000557e-01   1.10243696e-01   9.00367060e-01   7.46521199e-01
   6.62244261e-01   6.39755710e-01   2.89669250e-01   7.63405113e-01
   2.80009295e-01   1.36597737e-01   7.70010437e-01   7.01152203e-01
   4.05230500e-01   3.22750273e-01   7.40357460e-01   5.82020172e-01
   2.81460065e-02   8.60197432e-01   5.12439323e-01   3.37300976e-01
   8.64354419e-01   7.17844079e-01   3.97957357e-01   3.14932649e-01
   4.28855131e-01   1.39039654e-01   9.83528272e-01   3.06531725e-01
   1.30181163e-01   9.75811278e-01   2.48561878e-01   5.58077549e-01
   7.08686996e-01   2.33261356e-01   2.52092004e-01   5.04784840e-01
   3.85098648e-01   6.95070331e-01   3.64140144e-01   5.24609682e-01
   8.24068231e-02   8.21957085e-01   3.82714227e-01   8.25267952e-01
   1.25419813e-01   1.98059927e-01   7.95784613e-01   9.82368266e-02
   5.80655805e-01   4.00696680e-01   1.14599071e-01   1.91508432e-01
   5.28390472e-02   5.00226064e-01   7.77617962e-01   1.74828553e-01
   1.46664096e-01   2.54900672e-03   1.37880483e-01   6.96639237e-01
   6.37125436e-01   6.24599902e-01   5.85142866e-01   1.80906218e-02
   5.84181014e-01   8.89955346e-01   5.66001415e-01   8.83758323e-01
   9.29196386e-01   4.95540879e-01   5.38122395e-01   3.06210884e-01
   3.42315153e-01   7.01542985e-01   5.65995005e-01   4.05560813e-01
   8.14848941e-01   2.60412291e-01   6.08015891e-01   1.81245481e-01
   6.72642971e-01   2.21450547e-01   4.03355934e-02   2.53270905e-02
   8.80664696e-01   8.76901550e-01   7.67436135e-01   8.33610574e-01
   6.91109101e-01   2.23649220e-01   3.61893532e-01   5.93200579e-01
   2.55222100e-01   9.75223896e-01   5.65052658e-01   4.90460404e-01
   9.18317197e-01   6.63070320e-01   8.64615141e-01   3.78323054e-01
   6.12801706e-01   3.38115466e-01   4.05135596e-01   6.12015797e-01
   4.66638017e-01   8.70523074e-01   7.39559234e-04   8.76180159e-02
   8.71052273e-01   3.41279874e-01   4.54144169e-01   1.27780976e-01
   6.46129962e-02   2.81260085e-01   7.83169718e-01   6.07273123e-01
   9.47813646e-01   5.12307133e-01   5.04216449e-01   9.30425177e-01
   3.11614367e-01   3.95021913e-01   2.24301715e-01   2.57143527e-01
   4.06946968e-01   9.67541759e-01   9.01411200e-01   5.77546464e-01
   4.48530382e-02   1.84898302e-01   3.93231568e-01   7.60380611e-01
   8.32909824e-01   6.10799664e-01   2.40762730e-01   9.85094980e-01
   8.78426791e-01   4.62990742e-02   2.22678640e-02   3.40061682e-01
   3.97524273e-02   9.00130462e-01   6.51779944e-01   1.83394048e-01
   4.38050808e-01   7.21065152e-01   6.65957781e-01   4.73968161e-01
   3.36811934e-01   3.45224398e-02   1.81822044e-01   2.83182462e-01
   7.60833400e-01   4.98782814e-01   4.41173929e-01   9.88856247e-01
   7.78415342e-01   1.30842403e-01   3.80101085e-01   4.04428500e-01
   5.57084225e-01   3.13830966e-01   4.31645411e-01   2.35930783e-01
   4.44695188e-01   6.78144152e-02   2.84668718e-01   6.28757645e-01
   1.73349551e-02   7.25275972e-01   9.20248551e-01   6.71677562e-01
   5.95522487e-01   7.72201169e-01   7.59642525e-01   2.93270386e-01
   4.62805368e-02   1.17842679e-01   9.93487438e-01   9.43208910e-01
   1.83105273e-02   2.40582942e-01   9.51435942e-01   6.00917874e-01
   4.71977774e-02   4.49040901e-01   5.25594423e-01   8.84198165e-02
   9.27516777e-01   1.39756041e-01   6.49295671e-01   8.39320303e-01
   9.42472407e-01   6.47567426e-01   9.16814731e-01   1.56394569e-01
   3.60379537e-01   5.29118679e-01   1.36187866e-01   3.01760598e-01
   3.13171055e-01   1.83266156e-01   1.96724673e-01   1.00175427e-01
   8.73261214e-01   3.95420565e-01   1.98758430e-01   3.22090754e-01
   4.67114354e-01   7.94380647e-01   5.06631002e-01   7.37178234e-01
   4.05977795e-01   5.56654371e-01   3.47453273e-01   7.97783351e-01
   2.70793695e-01   3.86927152e-01   7.11423463e-02   3.23767697e-01
   8.24975653e-01   4.78047528e-01   4.62906034e-01   5.12759620e-01
   5.00982947e-01   1.62889479e-01   7.11344542e-01   5.29872147e-01
   6.69100443e-01   1.69676035e-01   1.52660792e-01   4.08582774e-01
   6.87356386e-01   9.18711624e-01   5.29935267e-01   6.38330709e-02
   2.95889525e-01   7.14599855e-01   2.16812322e-01   9.73940752e-01
   4.48403654e-01   7.11758837e-01   6.44107960e-01   9.13816291e-02
   6.79851277e-01   6.01338463e-01   1.61126214e-01   8.48900490e-01
   3.46243430e-01   7.74081419e-01   1.74900700e-01   7.68007388e-02
   1.06725726e-01   4.98952231e-01   1.19850169e-01   2.70019718e-01
   9.70022709e-01   3.01174990e-01   9.38084319e-01   2.02438705e-02
   4.18812242e-01   3.81694186e-01   7.65605344e-01   4.50768768e-01
   5.18305009e-01   2.67875932e-01   4.68181046e-01   9.39293571e-01
   3.20071605e-01   5.56678695e-01   3.81929131e-01   4.48828614e-02
   6.99869377e-01   3.23289601e-01   8.20147024e-01   7.06931505e-01
   6.06990251e-01   6.09106290e-02   2.51271327e-01   6.30816419e-02
   1.98199693e-01   1.96609794e-01   2.68131241e-01   1.74064417e-01
   9.52045778e-01   6.50550301e-01   9.48658927e-01   3.89386083e-01
   1.02453238e-01   5.76325743e-01   3.78949305e-01   7.06036069e-01
   6.28091286e-01   8.49627760e-01   9.84135658e-01   4.43709907e-01
   2.88180555e-01   5.27768576e-01   5.56126159e-01   6.90266477e-01
   2.96914239e-01   8.66082065e-01   1.72553350e-01   4.65556456e-01
   1.25427580e-01   9.11199102e-01   5.85260665e-01   8.36825754e-01
   7.93356073e-03   9.92917306e-01   6.73155782e-01   8.21795584e-01
   1.86642480e-01   2.07031339e-01   6.63101558e-01   8.71635738e-01
   7.39924159e-01   2.22151019e-01   2.22491438e-02   9.90650790e-01
   2.12120336e-01   4.66721084e-01   6.28660086e-01   7.57938089e-01
   9.16633997e-01   8.55785117e-01   4.82720298e-02   8.32500948e-01
   6.96823078e-01   9.12791895e-01   9.75188280e-01   9.27592421e-01
   5.98934487e-01   5.88522565e-01   1.95942293e-01   7.40921527e-01
   6.72371205e-01   7.37773873e-01   6.72959837e-01   2.01775710e-01
   2.57085250e-01   9.42197612e-01   4.70863456e-01   3.30665873e-01
   9.23047264e-01   6.31912836e-01   2.38027008e-01   5.08313268e-01
   4.08925615e-01   9.69155666e-01   2.72710517e-01   2.08748117e-01
   3.66061661e-01   7.99575916e-01   1.44328664e-01   4.35416316e-01
   7.14640879e-01   8.48818621e-01   2.51644177e-01   2.43944924e-01
   1.48262631e-01   5.74803383e-02   8.48306377e-01   6.18376357e-01
   9.02417307e-01   7.55157115e-02   8.16804162e-01   1.27595135e-01
   5.12094981e-01   8.71996617e-01   9.54296025e-01   8.88142726e-02
   1.51355827e-01   5.68541432e-01   8.57833319e-01   8.05033416e-01
   6.28174032e-01   9.98990569e-01   1.33320473e-01   1.14525101e-01
   2.42420734e-01   9.40557680e-01   1.62829710e-02   4.35991958e-01
   2.83418613e-01   7.47726831e-01   8.28131376e-01   6.01940891e-01
   2.84938297e-01   7.85977892e-01   8.57875124e-01   3.19533358e-01
   4.91476993e-01   6.27330413e-01   9.80206287e-01   5.85142698e-01
   4.86983768e-01   6.84566637e-01   8.65332020e-01   2.82181510e-01
   9.37606420e-01   3.18053825e-01   6.22934460e-01   6.02456351e-01
   7.23336733e-01   7.21621851e-01   2.27022142e-01   9.46682744e-01
   1.98359089e-01   6.87172883e-01   8.92497286e-01   8.47650480e-01
   2.93019622e-01   6.13359700e-02   6.28782959e-01   2.49272057e-01
   5.61165258e-01   2.24582383e-05   5.16017575e-01   2.66283648e-01
   9.36703828e-01   1.22966904e-01   6.07867820e-03   9.90891309e-02
   4.68862850e-01   2.70799941e-01   2.53872467e-03   9.98088266e-01
   1.23165295e-01   5.55448618e-02   8.85007399e-01   7.85879242e-01
   9.53051633e-01   1.48659345e-01   1.01170916e-01   7.41581494e-01
   6.57375278e-01   6.17591324e-01   6.86031373e-01   2.20350496e-01
   6.51169072e-01   8.98872339e-01   3.70935455e-01   3.15142734e-01
   4.72715821e-01   4.66132281e-02   6.98274096e-01   6.03591791e-01
   4.88240893e-01   5.73834604e-01   1.02495192e-01   7.76324560e-01
   6.14704482e-01   7.36832673e-01   9.56108865e-01   2.29164909e-01
   5.24369707e-01   6.61249494e-01   2.84893518e-01   2.75773116e-02
   6.53372487e-01   7.23974309e-01   1.72596420e-01   4.98671489e-01
   9.06150649e-01   7.03954411e-02   6.04109153e-01   1.31276339e-01
   1.83365461e-01   5.35564805e-01   9.48197875e-01   8.99347207e-01
   6.33226047e-01   8.40569367e-01   2.43335270e-01   4.28295118e-01
   2.72951290e-01   8.07776412e-01   4.84620198e-01   2.65715439e-01
   8.78096392e-02   2.46185011e-01   2.94515994e-01   8.27434413e-01
   3.83315646e-01   9.91245022e-01   9.47243714e-02   1.48126259e-01
   5.38163650e-01   9.27494549e-01   9.28823394e-01   5.88130248e-01
   6.98925042e-01   4.83118385e-01   4.15185271e-02   3.77215011e-01
   6.05935033e-01   4.81991239e-01   1.43268153e-03   9.31557671e-01
   8.22957794e-01   3.11212268e-02   7.99670786e-01   5.41071687e-01
   2.86861600e-01   8.33273328e-01   7.63562553e-01   5.00601881e-01
   3.45727678e-01   5.56063494e-01   7.23757292e-01   2.69046643e-01
   2.50150144e-01   8.78840432e-01   9.85978949e-01   9.79990499e-01
   2.74339636e-01   4.60610737e-01   7.31273305e-01   9.19146410e-01
   6.55808012e-02   9.71384016e-01   2.42255564e-01]